### ISSUE TITLE
Release this repl to play store

### ISSUE THREAD

**Issue by Gonzih** [tahmidsadik112/Replicator#8]
Hi,

First of all I must say this is great!
Seeing cljs on our beloved android makes me happy, well done!

But it would be great to have this demo app in a google play store.
That wolud be much simpler way to demonstrate benefits of using cljs on android withoun any need to install android related tooling.

What do you think? Do you have plans for that? Do you need help?

**Comment by tahmidsadik** [comment]
I am not releasing it because there are some big performance issues. It takes almost 10 seconds to prepare the REPL in a simulator and 30 seconds in my nexus 7.
I am currently using Rhino for executing javascript but it's very slow in android and it demands a lot of ram which in turn causes the GC to get called repeatedly. So I am planning to use JavascriptCore with a native module. JSCore is a lot faster than Rhino and using native module would give us more control over memory usage and GC. 

As of now I am trying to build JSCore to use with Android. Help in this area will be much appreciated.

**Comment by Gonzih** [comment]
I'm not well familiar with JSCore. Is there any particular benefit using it instead of for example v8 on android?

**Comment by tahmidsadik** [comment]
Facebook's React-Native project is using JavascriptCore in Android. I believe using JavascriptCore as the execution engine should at least simplify things to drive React-Native from Clojurescript.

**Comment by Gonzih** [comment]
Ok, I see. Is it possible to ask people behind react native on how they compile jscore for android? :)

**Comment by Gonzih** [comment]
Have you seen this project (I think you did, but nevertheless) https://github.com/ericwlange/AndroidJSCore

**Comment by tahmidsadik** [comment]
This project links to https://github.com/appcelerator/hyperloop/wiki/Building-JavaScriptCore-for-Android for building JSCore and I am trying to follow their instructions. Hopefully I will succeed. :)

**Comment by Gonzih** [comment]
Yeah, looks like those instructions are outdated. What repo do you use as initial one instead of matt-langston/webkit?

**Comment by tahmidsadik** [comment]
I horribly failed. I think we should ask for help to the R-N guys of Facebook.

**Comment by tahmidsadik** [comment]
I found this webkit repo https://github.com/WebKit/webkit

**Comment by Gonzih** [comment]
After couple of evenings fighting with webkit for android and tooling around build process I gave up. At least for now :)
